# fly.toml app configuration file generated for freedaychekerbot on 2026-08-18T20:59:16+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'freedaychekerbot'
primary_region = 'sin'

[build]
[env]
  BOT_DATA_DIR = '/data'

[[mounts]]
  source = 'bot_data'
  destination = '/data'

[[vm]]
  size = 'shared-cpu-1x'
